Use RScript to determine the arch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,6 +2,8 @@
 # This is based on the configure script of the gifski package, (https://github.com/r-rust/gifski/),
 # distributed under the MIT license, authored by Jeroen Ooms.
 
+RSCRIPT="${R_HOME}/bin/Rscript"
+
 # 1.41.0 is the min version among Debian and Ubuntu at the time of writing this
 # (c.f. https://github.com/ron-rs/ron/issues/256#issuecomment-657999081)
 # This might need bumped depending on the features the crate uses. cargo-msrv
@@ -78,13 +80,21 @@ fi
 echo "*** Trying to download the precompiled binary"
 
 if [ "`uname`" = "Darwin" ]; then
-  if [ "`uname -m`" = "x86_64" ]; then
-    RUST_TARGET="x86_64-apple-darwin"
-    SHA256SUM_EXPECTED="${SHA256SUM_X86_64}"
-  elif [ "`uname -m`" = "arm64" ]; then
-    RUST_TARGET="aarch64-apple-darwin"
-    SHA256SUM_EXPECTED="${SHA256SUM_ARM64}"
-  fi
+  # For some reason, it seems uname -m or arch cannot be used reliably (why?)
+  MAC_ARCH=`"${Rscript}" -e 'cat(R.version$arch)'`
+  case "${MAC_ARCH}" in
+    x86_64)
+      RUST_TARGET="x86_64-apple-darwin"
+      SHA256SUM_EXPECTED="${SHA256SUM_X86_64}" ;;
+    arm64)
+      RUST_TARGET="aarch64-apple-darwin"
+      SHA256SUM_EXPECTED="${SHA256SUM_ARM64}" ;;
+    *)
+      echo ""
+      echo "ERROR: Unexpected arch: ${MAC_ARCH}"
+      echo ""
+      exit 5
+  esac
 
   SRC="https://github.com/${GITHUB_REPO}/releases/download/${GITHUB_TAG}/${RUST_TARGET}-lib${CRATE_NAME}.a"
   DST="./src/rust/target/release/lib${CRATE_NAME}.a"
@@ -92,7 +102,7 @@ if [ "`uname`" = "Darwin" ]; then
   echo "*** Download URL: ${SRC}"
   echo "*** Dest file: ${DST}"
 
-  "${R_HOME}/bin/Rscript" ./tools/download_precompiled_binary.R "${SRC}" "${DST}"
+  "${RSCRIPT}" ./tools/download_precompiled_binary.R "${SRC}" "${DST}"
   if [ $? -ne 0 ]; then
     echo ""
     echo "ERROR: Failed to download the pre-compiled binary"
